### PR TITLE
Add Paulo Gomes to the security team

### PR DESCRIPTION
**Pull request by pjbgf**
Reasoning:
- Maintainer of some Flux repositories, [expanding to Flux2](https://github.com/fluxcd/flux2/pull/2638).
- Background working with Kubernetes and cloud security.
- Focused on various security related PRs/Issues across Flux repositories.
- Keen on working on research and improving processes around Flux's security.

### CODE REVIEW

**Comment by dholbach** [comment]
Big :heavy_plus_sign: from my end. I had a the big pleasure of working with @pjbgf on the security blog posts and learned a lot this way! Thanks for offering your help!

**Comment by pjbgf** [comment]
Can I get @fluxcd/flux2-maintainers to vote on this issue please?

**Comment by makkes** [comment]
+1 from me

**Review by scottrigby — APPROVED** [review]
+💯 from me @pjbgf You are in practice a critical part of the Flux security team. This just formalizes it.

**Review by hiddeco — APPROVED** [review]
+1 from me

**Comment by darkowlzz** [comment]
+1 from me

**Review by relu — APPROVED** [review]

**Review by stefanprodan — APPROVED** [review]

**Pull request merged**
