### PR TITLE
Add Matheus Pimenta to the security team

### PR DESCRIPTION
**Pull request by matheuscscp**
@fluxcd/core-maintainers 

### Applying as a Security Team member

**Process:**

- [x] You need to be a Maintainer to be able to apply
- [x] Set up your [Keybase](https://keybase.io) account
- [x] Make a PR against the `SECURITY.md` file in <https://github.com/fluxcd/.github> adding your contact information
- [x] @mention `@fluxcd/core-maintainers`
- [x] Have maintainers submit their vote by `+1`
- [x] Once all maintainers in repo have `+1` the PR will be reviewed by a member of the [core maintainers]

Adding new Security Team members is an [Unanimity decision](https://github.com/fluxcd/community/blob/main/GOVERNANCE.md#unanimity-decisions).

Once the above process has taken its course, make sure you

- [ ] Ping [CNCF Service Desk](https://cncfservicedesk.atlassian.net/) to get you added as [Security Team member].
- [x] Make a PR against [oss-fuzz](https://github.com/google/oss-fuzz/blob/e51830c2d428e672b405f9692adc82c57c1a6c5a/projects/fluxcd/project.yaml#L4-L9) to add your email.
- [ ] Ping fellow Security Team members to give you access to all the internal information.

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
+1

**Review by pjbgf — APPROVED** [review]
+1

**Comment by makkes** [comment]
+1

**Review by relu — APPROVED** [review]
+1

**Comment by hiddeco** [comment]
+1

**Review by aryan9600 — APPROVED** [review]
+1

**Comment by riaankleinhans** [comment]
A service desk access invitation have been sent to @matheuscscp
Please accept the invitation to complete the process.

**Comment by matheuscscp** [comment]
@riaankleinhans Accepted!

**Comment by RobertKielty** [comment]
I've added @matheuscscp to the mailing list, welcome aboard! 🫡

**Comment by matheuscscp** [comment]
I suppose this is done:

> Ping CNCF Service Desk to get you added as [Security Team member].

**Comment by matheuscscp** [comment]
@pjbgf I think only this is missing now:

> Ping fellow Security Team members to give you access to all the internal information.

**Comment by matheuscscp** [comment]
Checklist completed 🙌

**Comment by matheuscscp** [comment]
Thanks @RobertKielty, where can I open up the list to check the last msg?

**Pull request merged**
